name: publication
on:
  push:
    branche: [ main ]
  pull_request:
    branche: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  site:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dépendances
      run: npm install
    - name: génération du site
      run: npm run build
    - name: publication du site
      uses: actions/upload-pages-artifact@v1
      with:
        path: www
    - name: publication du site étape 2
      id: deployment
      uses: actions/deploy-pages@v2
